import os
import argparse
import pprint as pp
import sys
from pathlib import Path

import torch

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from data.utils.utils import *

OPEN_PROBLEMS = {
    "OVRP",
    "OVRPTW",
    "OVRPB",
    "OVRPL",
    "OVRPBL",
    "OVRPBTW",
    "OVRPLTW",
    "OVRPBLTW",
}

BACKHAUL_PROBLEMS = {
    "VRPB",
    "OVRPB",
    "VRPBL",
    "VRPBTW",
    "VRPBLTW",
    "OVRPBL",
    "OVRPBTW",
    "OVRPBLTW",
}

ROUTE_LIMIT_PROBLEMS = {
    "VRPL",
    "OVRPL",
    "VRPBL",
    "OVRPBL",
    "VRPLTW",
    "OVRPLTW",
    "VRPBLTW",
    "OVRPBLTW",
}

TW_PROBLEMS = {
    "VRPTW",
    "OVRPTW",
    "VRPBTW",
    "OVRPBTW",
    "VRPLTW",
    "OVRPLTW",
    "VRPBLTW",
    "OVRPBLTW",
}


def to_int_coord(value, scale=1000):
    return int(round(float(value) * scale))


def unpack_instance(problem, item):
    fields = {
        "depot_xy": item[0],
        "node_xy": item[1],
        "node_demand": item[2],
        "capacity": item[3] if len(item) > 3 else None,
        "route_limit": None,
        "service_time": None,
        "tw_start": None,
        "tw_end": None,
    }

    if problem in ROUTE_LIMIT_PROBLEMS:
        fields["route_limit"] = item[4]

    if problem in TW_PROBLEMS and problem in ROUTE_LIMIT_PROBLEMS:
        fields["service_time"] = item[5]
        fields["tw_start"] = item[6]
        fields["tw_end"] = item[7]
    elif problem in TW_PROBLEMS:
        fields["service_time"] = item[4]
        fields["tw_start"] = item[5]
        fields["tw_end"] = item[6]

    return fields


def write_vrplib(path, name, problem, fields):
    depot_xy = fields["depot_xy"]
    node_xy = fields["node_xy"]
    node_demand = fields["node_demand"]
    capacity = fields["capacity"]
    dimension = len(node_xy) + 1
    backhauls = [idx + 2 for idx, demand in enumerate(node_demand) if demand < 0]

    header = [
        f"NAME : {name}",
        f'COMMENT : "Generated by pyvrp_manuel ({problem})"',
        f"TYPE : {problem}",
        f"DIMENSION : {dimension}",
        "EDGE_WEIGHT_TYPE : EUC_2D",
    ]

    if capacity is not None:
        header.append(f"CAPACITY : {int(round(capacity))}")

    if problem != "CVRP":
        header.append(f"VEHICLES : {len(node_xy)}")

    if problem in OPEN_PROBLEMS:
        header.append("OPEN_ROUTE : YES")

    if fields["route_limit"] is not None:
        header.append(f"DISTANCE : {to_int_coord(fields['route_limit'])}")

    if fields["service_time"] is not None:
        header.append(f"SERVICE_TIME : {to_int_coord(fields['service_time'][0])}")

    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(header))
        fh.write("\n")
        fh.write("NODE_COORD_SECTION\n")
        fh.write(f"1\t{to_int_coord(depot_xy[0][0])}\t{to_int_coord(depot_xy[0][1])}\n")

        for idx, xy in enumerate(node_xy, start=2):
            fh.write(f"{idx}\t{to_int_coord(xy[0])}\t{to_int_coord(xy[1])}\n")

        fh.write("DEMAND_SECTION\n")
        fh.write("1\t0\n")
        for idx, demand in enumerate(node_demand, start=2):
            fh.write(f"{idx}\t{abs(int(round(demand)))}\n")

        if fields["tw_start"] is not None:
            fh.write("TIME_WINDOW_SECTION\n")
            fh.write(f"1\t0\t{to_int_coord(3)}\n")
            for idx, (tw_start, tw_end) in enumerate(zip(fields["tw_start"], fields["tw_end"]), start=2):
                fh.write(f"{idx}\t{to_int_coord(tw_start)}\t{to_int_coord(tw_end)}\n")

        if backhauls:
            fh.write("BACKHAUL_SECTION\n")
            fh.write("\t".join(str(idx) for idx in backhauls))
            fh.write("\t-1\n")

        fh.write("DEPOT_SECTION\n")
        fh.write("1\n")
        fh.write("-1\n")
        fh.write("EOF\n")


def generate_vrp_files(env, num_samples, problem_size, out_dir):
    data = env.get_random_problems(num_samples, problem_size, normalized=False)
    dataset = [attr.cpu().tolist() for attr in data]
    instances = list(zip(*dataset))

    for idx, item in enumerate(instances, start=1):
        fields = unpack_instance(env.problem, item)
        n = len(fields["node_xy"]) + 1
        node_dir = os.path.join(out_dir, str(n))
        os.makedirs(node_dir, exist_ok=True)
        name = f"n{n}-{idx:04d}"
        path = os.path.join(node_dir, f"{name}.vrp")
        write_vrplib(path, name, env.problem, fields)
        print(f"Save {env.problem} VRPLIB instance to {path}")


if __name__ == "__main__":
    cfg = load_data_config()
    default_generated_dir = os.path.abspath(
        os.path.join(
            os.path.dirname(__file__),
            "..",
            get_config_value(cfg, "paths", "generated_dir", "generated"),
        )
    )

    parser = argparse.ArgumentParser(description="Generate datasets")
    parser.add_argument('--problem', type=str, default="ALL", choices=["Train_ALL", "ALL", "CVRP", "OVRP", "VRPB", "VRPL", "VRPTW", "OVRPTW",
                                                                       "OVRPB", "OVRPL", "VRPBL", "VRPBTW", "VRPLTW",
                                                                       "OVRPBL", "OVRPBTW", "OVRPLTW", "VRPBLTW", "OVRPBLTW"])
    parser.add_argument('--problem_size', type=int, default=50)
    parser.add_argument('--pomo_size', type=int, default=50, help="the number of start node, should <= problem size")
    parser.add_argument('--num_samples', type=int, default=1000)
    parser.add_argument('--seed', type=int, default=get_config_value(cfg, "generate", "seed", 0))
    parser.add_argument('--dir', type=str, default=default_generated_dir)
    parser.add_argument('--format', type=str, default="vrp", choices=["pkl", "vrp"])
    parser.add_argument('--no_cuda', action='store_true', default=True)
    parser.add_argument('--gpu_id', type=int, default=0)

    args = parser.parse_args()
    pp.pprint(vars(args))
    env_params = {"problem_size": args.problem_size, "pomo_size": args.pomo_size}
    seed_everything(args.seed)

    args.device = torch.device('cpu')
    torch.set_default_tensor_type('torch.FloatTensor')
    print(">> SEED: {}, USE_CUDA: False, CUDA_DEVICE_NUM: {}".format(args.seed, args.gpu_id))
    env_params["device"] = args.device

    envs = get_env(args.problem)
    for env in envs:
        env = env(**env_params)
        if args.format == "vrp":
            generate_vrp_files(
                env=env,
                num_samples=args.num_samples,
                problem_size=args.problem_size,
                out_dir=os.path.join(args.dir, env.problem),
            )
        else:
            dataset_path = os.path.join(args.dir, env.problem, "{}{}_uniform.pkl".format(env.problem.lower(), args.problem_size))
            env.generate_dataset(args.num_samples, args.problem_size, dataset_path)
            env.load_dataset(dataset_path, num_samples=args.num_samples, disable_print=False)
